/pid_controller:
  ros__parameters:
    kd: 0.1
    ki: 0.0
    kp: 0.5
    goal_reach_tol: 0.01
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false
