/turtle1/pid_controller:
  ros__parameters:
    kd: 0.01
    ki: 0.0001
    kp: 0.7
    goal_reach_tol: 0.05
    max_linear_velocity: 50.0
    max_angular_velocity: 100.0
    max_linear_acceleration: 0.2
    max_linear_deceleration: 0.6
    add_acce_deccl_limits: false

    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

/turtle1/rotate_turtle_goal_three:
  ros__parameters:
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    radius: 4.0
    speed: 1.0
    use_sim_time: false


############################################################################
/turtle2/pid_controller:
  ros__parameters:
    kd: 0.005
    ki: 0.001
    kp: 0.9
    goal_reach_tol: 0.09
    max_linear_velocity: 0.5
    max_angular_velocity: 1.0
    max_linear_acceleration: 0.6
    max_linear_deceleration: 0.6
    add_acce_deccl_limits: true
    
    qos_overrides:
      /parameter_events:
        publisher:
          depth: 1000
          durability: volatile
          history: keep_last
          reliability: reliable
    use_sim_time: false

